// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proxy/snell/config.proto

package snell

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account 是 Snell 的用户凭据。Snell 用 PSK(预共享密钥)派生 AEAD key(Argon2id),
// 多用户时服务端用每个用户的 PSK 逐一试解首个 record(类似 shadowsocks AEAD)。
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Psk   string                 `protobuf:"bytes,1,opt,name=psk,proto3" json:"psk,omitempty"`
	// 协议版本:4 / 5 / 6。0 视为默认(4)。v4/v5 线路等价,v6 引入流量整形。
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// 混淆(仅 v4/v5):"" | "http" | "tls"。
	ObfsMode string `protobuf:"bytes,3,opt,name=obfs_mode,json=obfsMode,proto3" json:"obfs_mode,omitempty"`
	ObfsHost string `protobuf:"bytes,4,opt,name=obfs_host,json=obfsHost,proto3" json:"obfs_host,omitempty"`
	// v6 整形模式:"" | "default" | "unshaped" | "unsafe-raw"(仅 v6)。
	V6Mode string `protobuf:"bytes,5,opt,name=v6_mode,json=v6Mode,proto3" json:"v6_mode,omitempty"`
	// v6 多用户标识(clientID/userKey);v6 用共享 PSK + clientID 区分用户。
	ClientId      string `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_snell_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_snell_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_snell_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetPsk() string {
	if x != nil {
		return x.Psk
	}
	return ""
}

func (x *Account) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Account) GetObfsMode() string {
	if x != nil {
		return x.ObfsMode
	}
	return ""
}

func (x *Account) GetObfsHost() string {
	if x != nil {
		return x.ObfsHost
	}
	return ""
}

func (x *Account) GetV6Mode() string {
	if x != nil {
		return x.V6Mode
	}
	return ""
}

func (x *Account) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_snell_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_snell_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_snell_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server.User 携带 Account(psk/version/obfs)。
	Server        *protocol.ServerEndpoint `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_snell_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_snell_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_snell_config_proto_rawDescGZIP(), []int{2}
}

func (x *ClientConfig) GetServer() *protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

var File_proxy_snell_config_proto protoreflect.FileDescriptor

const file_proxy_snell_config_proto_rawDesc = "" +
	"\n" +
	"\x18proxy/snell/config.proto\x12\x10xray.proxy.snell\x1a\x1acommon/protocol/user.proto\x1a!common/protocol/server_spec.proto\"\xa5\x01\n" +
	"\aAccount\x12\x10\n" +
	"\x03psk\x18\x01 \x01(\tR\x03psk\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1b\n" +
	"\tobfs_mode\x18\x03 \x01(\tR\bobfsMode\x12\x1b\n" +
	"\tobfs_host\x18\x04 \x01(\tR\bobfsHost\x12\x17\n" +
	"\av6_mode\x18\x05 \x01(\tR\x06v6Mode\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\"@\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\"L\n" +
	"\fClientConfig\x12<\n" +
	"\x06server\x18\x01 \x01(\v2$.xray.common.protocol.ServerEndpointR\x06serverBR\n" +
	"\x14com.xray.proxy.snellP\x01Z%github.com/xtls/xray-core/proxy/snell\xaa\x02\x10Xray.Proxy.Snellb\x06proto3"

var (
	file_proxy_snell_config_proto_rawDescOnce sync.Once
	file_proxy_snell_config_proto_rawDescData []byte
)

func file_proxy_snell_config_proto_rawDescGZIP() []byte {
	file_proxy_snell_config_proto_rawDescOnce.Do(func() {
		file_proxy_snell_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_snell_config_proto_rawDesc), len(file_proxy_snell_config_proto_rawDesc)))
	})
	return file_proxy_snell_config_proto_rawDescData
}

var file_proxy_snell_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxy_snell_config_proto_goTypes = []any{
	(*Account)(nil),                 // 0: xray.proxy.snell.Account
	(*ServerConfig)(nil),            // 1: xray.proxy.snell.ServerConfig
	(*ClientConfig)(nil),            // 2: xray.proxy.snell.ClientConfig
	(*protocol.User)(nil),           // 3: xray.common.protocol.User
	(*protocol.ServerEndpoint)(nil), // 4: xray.common.protocol.ServerEndpoint
}
var file_proxy_snell_config_proto_depIdxs = []int32{
	3, // 0: xray.proxy.snell.ServerConfig.users:type_name -> xray.common.protocol.User
	4, // 1: xray.proxy.snell.ClientConfig.server:type_name -> xray.common.protocol.ServerEndpoint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_snell_config_proto_init() }
func file_proxy_snell_config_proto_init() {
	if File_proxy_snell_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_snell_config_proto_rawDesc), len(file_proxy_snell_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_snell_config_proto_goTypes,
		DependencyIndexes: file_proxy_snell_config_proto_depIdxs,
		MessageInfos:      file_proxy_snell_config_proto_msgTypes,
	}.Build()
	File_proxy_snell_config_proto = out.File
	file_proxy_snell_config_proto_goTypes = nil
	file_proxy_snell_config_proto_depIdxs = nil
}
